//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla_IRP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Db : global::System.Configuration.ApplicationSettingsBase {
        
        private static Db defaultInstance = ((Db)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Db())));
        
        public static Db Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db\\\\Commons")]
        public string CommonsDbPath {
            get {
                return ((string)(this["CommonsDbPath"]));
            }
            set {
                this["CommonsDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db")]
        public string DbSuffix {
            get {
                return ((string)(this["DbSuffix"]));
            }
            set {
                this["DbSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db\\\\Production")]
        public string ProductionDbPath {
            get {
                return ((string)(this["ProductionDbPath"]));
            }
            set {
                this["ProductionDbPath"] = value;
            }
        }
    }
}
