//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRP.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AFI,Afinado,Mayor 
        ///AG,Aguja,Crítico 
        ///AL,Aleta cortante cuerpo,Crítico 
        ///ALB,Aleta Boca,Crítico 
        ///ALC,Aleta en cuerpo no cortante,Mayor 
        ///BA,Boca arrancada,Mayor 
        ///BCA,Boca caída,Mayor 
        ///BDF,Boca Deformada,Mayor 
        ///BDZ,Boca Descentrada,Mayor 
        ///BGI,Boca Girada,Mayor 
        ///BH,Boca Hinchada,Mayor 
        ///BML,Boca Mal Llena,Mayor 
        ///BOV,Boca Ovalizada,Mayor 
        ///BR,Boca Rajada,Mayor 
        ///BRS,Boca rajada suceptible de rotura,Crítico 
        ///BS,Boca Sucia,Menor 
        ///BU&lt;,Bullones &lt;5mm,Menor 
        ///BU&gt;,Bullón &gt;5mm,Mayor 
        ///BUB,Bullón Boca,Mayor         /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Defects {
            get {
                return ResourceManager.GetString("Defects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crítico, 1
        ///Mayor, 2
        ///Menor, 3
        ///Embalaje, 4.
        /// </summary>
        internal static string DefectTypes {
            get {
                return ResourceManager.GetString("DefectTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11
        ///11A
        ///11B
        ///12
        ///12A
        ///12B
        ///13.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEITE MORO 50 AV, 7171WA                                                                                                                                                                                                                                       
        ///ANFORA 50 AV, 6557WB                                                                                                                                                                                                                                           [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APR,
        ///Reinyectado,
        ///Reescogido,
        ///Transferencia.
        /// </summary>
        internal static string PaletRejectStates {
            get {
                return ResourceManager.GetString("PaletRejectStates", resourceCulture);
            }
        }
    }
}
